// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 Learning Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ros2-learning-module',
        },
        {
          type: 'autogenerated',
          dirName: 'ros2-digital-twin-module',
        },
      ],
    },
  ],
};

export default sidebars;
